### ISSUE TITLE
problem with pasta

### ISSUE THREAD

**Issue by ChaoShenzjs** [smirarab/pasta#64]
hi there,
 I  installed pasta in a linux system following the instruction, it seems successful. but when I try run_pasta.py and some problems occcured showed: ImportError: cannot import name convert node to root polytomy. How do deal with it?
Many thanks!

**Comment by seansolari** [comment]
I came across a similar issue, being the following python error (using Python 3.10):

`ImportError: cannot import name '_convert_node_to_root_polytomy' from 'dendropy.datamodel.treemodel'`

This is due to an update in Dendropy (a dependency of PASTA) from v4.5.1 to v4.6.0. Installing specifically Dendropy v4.5.1 (eg. `python -m pip install dendropy==4.5.1`) solved this issue for me.

**Comment by simeonborko** [comment]
Actually version 4.5.2 works as well as this comment says: https://github.com/smirarab/sepp/pull/126#issuecomment-1636698661

I'll create a pull request to fix that version and a new issue to adapt pasta code for the newest version of dendropy.

**Comment by smirarab** [comment]
6f3ff8907547d31f18485118aea7a79be2e98d3f fixes for now. We use issue #67 to track this. So, I'll close this one.

**Comment by JCSzamosi** [comment]
I have encountered this same error after installing SEPP with conda. Is it possible the correct dependencies have not been set up there?
